apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        env:
        # Variables mínimas para que funcione
        - name: WORDPRESS_DB_HOST
          value: "localhost"
        - name: WORDPRESS_DB_USER
          value: "test"
        - name: WORDPRESS_DB_PASSWORD
          value: "test"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 3002
    targetPort: 80